# Generated by Django 2.2.6 on 2019-10-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_desc',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
